application:
  name: echo
  namespace: echo
  version: "1.0"
  image: nginx:1.21.1-alpine
  kind: deployment
  port: 80
  protocol: HTTP

env:          
  FOO: "BAR"
  PING: "PONG"
  ENVIRONMENT: "dev"

replicas: 
  desired: 2
  minimum: 2
  maximum: 6

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi  

probe:
  startup:
    enabled: false
    path: /
    failureThreshold: 10
    periodSeconds: 10
  liveness:
    enabled: false
    path: /
    failureThreshold: 10
    periodSeconds: 10
  readiness:
    enabled: false
    path: /
    failureThreshold: 10
    periodSeconds: 10

prometheus:
  scrape: false
  path: /metrics

autoscaling:
  hpa:
    cpu: 
      enabled: true
      averageUtilization: 80
    memory:
      enabled: false
      averageUtilization: 80

ingress:
  host: echo.local.cluster
  
availability:
  multiaz: 
    mode: soft # Ex; soft or hard

  same-host: 
    mode: soft # Ex; soft or hard