{{ if .Values.autoscaling.hpa.cpu.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.application.name }}-hpa-cpu
  namespace: {{ .Values.application.namespace }}
spec:
  maxReplicas: {{ .Values.replicas.maximum }}
  minReplicas: {{ .Values.replicas.minimum }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.cpu.averageUtilization }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.application.name }}
{{ end }}