apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - {{ .Values.application.name }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host:     {{ .Values.application.name }}
        port:
          number: {{ .Values.application.port }}
    retries:
      attempts:       {{ .Values.retry.max_attemps }}
      {{ if .Values.retry.timeout.enabled }}
      perTryTimeout:  {{ .Values.retry.timeout.max_timeout }}
      {{ end }}
      {{ if .Values.retry.error.enabled }}
      retryOn:        {{ .Values.retry.error.errors }}
      {{ end }}