apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.application.name }}-gateway
  namespace: {{ .Values.application.namespace }}
spec:
  selector:
    istio: ingressgateway 
  servers:
  - port:
      name: http
      number: {{ .Values.application.port }}
      protocol: {{ .Values.application.protocol }}
    hosts:
    - {{ .Values.ingress.host }}