apiVersion: v1
kind: Service
metadata:
  name:       {{ .Values.application.name }}
  namespace:  {{ .Values.application.namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.application.port }}"    
  labels:
    app.kubernetes.io/name:     {{ .Values.application.name }}
    app.kubernetes.io/instance: {{ .Values.application.name }} 
spec:
  ports:
  - name: http
    port:     {{ .Values.application.port }}
    protocol: TCP
  selector:
    app:      {{ .Values.application.name }}
  type: ClusterIP