application:
  name: chip
  namespace: chip
  version: "1.0"
  image: fidelissauro/chip:latest
  kind: deployment
  port: 8080
  protocol: HTTP

env:
  CHAOS_ENABLED: "true"
  ENVIRONMENT: "dev"
  VERSION: "v1-complete"

replicas:
  desired: 2
  minimum: 2
  maximum: 2

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

probe:
  startup:
    enabled: false
    path: /healthcheck
    failureThreshold: 10
    periodSeconds: 10
  liveness:
    enabled: false
    path: /liveness
    failureThreshold: 10
    periodSeconds: 10
  readiness:
    enabled: true
    path: /readiness
    failureThreshold: 10
    periodSeconds: 10

prometheus:
  scrape: true
  path: /metrics

autoscaling:
  hpa:
    cpu:
      enabled: true
      averageUtilization: 80
    memory:
      enabled: true
      averageUtilization: 80

# High Availability Setup
availability:
  multiaz: 
    enabled: true
    mode: soft # Ex; soft or hard

  host: 
    enabled: true
    mode: soft # Ex; soft or hard

# Retry Options - Envoy
retry:
  max_attemps: 2
  timeout: 
    enabled: true
    max_timeout: 4s
  error:
    enabled: true
    errors: gateway-error,connect-failure,refused-stream,5xx

# Circuit Breaking
circuit_breaker:
  enabled: true
  max_connections: 500
  max_pending_requests: 20
  max_requests_per_connection: 20
  max_consecutive_5xx_errors: 50
  evaluation_interval: 1s
  ejection_time: 10s
  ejection_percent: 100

ingress:
  host: chip.k8s.raj.ninja