application:
  name: simple
  namespace: simple
  version: "1.0"
  image: fidelissauro/chip:latest
  kind: deployment
  port: 8080
  protocol: HTTP

env:
  ENVIRONMENT: "dev"
  VERSION: "simple-v1"

replicas:
  desired: 2
  minimum: 2
  maximum: 6

probe:
  readiness:
    enabled: true
    path: /healthcheck
    failureThreshold: 10
    periodSeconds: 10

ingress:
  host: simple.k8s.raj.ninja