application:
  name: retry-app
  namespace: retry-app
  version: "1.0"
  image: fidelissauro/chip:latest
  kind: deployment
  port: 8080
  protocol: HTTP

env:
  ENVIRONMENT: "dev"
  VERSION: "retry-v1"

replicas:
  desired: 2
  minimum: 2
  maximum: 6

probe:
  readiness:
    enabled: true
    path: /healthcheck
    failureThreshold: 10
    periodSeconds: 10

retry:
  max_attemps: 2
  timeout: 
    enabled: true
    max_timeout: 4s
  error:
    enabled: true
    errors: gateway-error,connect-failure,refused-stream,5xx

ingress:
  host: retry-app.k8s.raj.ninja